# Generated by Django 5.0.7 on 2024-08-05 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='construction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engineer_name', models.CharField(max_length=20)),
                ('work_type', models.CharField(choices=[('house', 'house'), ('villa', 'villa'), ('flat', 'flat')], max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('due_date', models.DateField()),
                ('fund_allocated', models.FloatField()),
            ],
        ),
    ]
